name: CI
on: 
  push:
    tags:
      - v*
permissions:
  contents: read
env:
  NODE_VERSION: 18
jobs:
  setup:
    if: github.repository_owner == 'Xzonn' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: ${{ startsWith(github.ref, 'refs/tags/v') && 'release' || '' }}

      - name: Cache setup
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.ref }}-${{ github.sha }}-setup

  publish-npm:
    needs: setup
    if: github.repository_owner == 'Xzonn' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Restore setup
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.ref }}-${{ github.sha }}-setup

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Publish to NPM
        run: |
          TAG=$(echo $GITHUB_REF_NAME | grep -oP '^v\d+\.\d+\.\d+-?\K(\w+)?')
          npm publish --tag ${TAG:-latest}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}